fix: set to null undefined keys
HwdGroup/hwd-aggregator pull request #4
Opened 2017-04-17 16:43 UTC by juanem1

En base a los comentarios de https://github.com/HwdGroup/aws-resources/pull/123#discussion_r111163970 agrego una condición de que si la key es undefined la seteo como null.

- [x] Easy to rollback to the previous state
- [x] Works fine with the old state in parallel (backward compatible)
- [x] It doesn't depend on other branches/PR

2017-04-17 17:03 UTC, nitely commented on src/index.js
> +      increment[field] = rawRecord[field] || null;
`rawRecord[field]` nunca va a ser `0` o `false`?

2017-04-17 17:46 UTC, juanem1 commented on src/index.js
> +      increment[field] = rawRecord[field] || null;
@nitely Calculo que si pero, en ese caso te quedaria null.
Sino, puedo agregar un if únicamente para validar si el valor es undefined y lo demas que se asigne lo que viene.
@leamarty

2017-04-17 18:47 UTC, leamarty requested changes

2017-04-17 18:47 UTC, leamarty commented on src/index.js
> +      increment[field] = rawRecord[field] || null;
Sí, hagamos eso. Pongamos que ````rawRecord[field] === undefined ? null : rawRecord[field]```` y sale como trompada

2017-04-17 19:17 UTC, juanem1 commented
@nitely @leamarty Listo

2017-04-18 17:12 UTC, leamarty approved these changes

2017-04-18 17:14 UTC, nitely approved these changes

2017-04-18 17:30 UTC, merged